import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { cookies } from "next/headers";
import LogOutButton from "./login/LogOutButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const token = cookieStore.get("token");
  const IS_DEV_MODE = process.env.NODE_ENV !== "production";

  const userRes = await fetch(`${process.env.API_URL}/auth/userFromToken`, {
    method: "GET",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${token?.value}`,
    },
  });

  const user = userRes.ok ? await userRes.json() : null;

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {IS_DEV_MODE && <h1 className="flex justify-center items-center bg-red-600 min-h-10 font-bold text-green-300 animate-bounce">Dev Mode is on - SECURITY LOW (set NODE_ENV=production)</h1>}
        {children}
      </body>
    </html>
  );
}
